services:
  geofence:
    image: geofence
    container_name: geofence
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3010:3010"
    environment:
      - GOMAXPROCS
      - GOGC=off
      - GOMEMLIMIT
    networks:
      - service-network

  init-migrate-seed:
    image: geofence
    pull_policy: never
    container_name: init-migrate-seed
    restart: unless-stopped
    entrypoint: ['./app/admin', 'migrate-seed']
    environment:
      - GEOFENCE_DB_USER=postgres
      - GEOFENCE_DB_PASSWORD=postgres
      - GEOFENCE_DB_HOST=database
      - GEOFENCE_DB_DISABLE_TLS=true  
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - database
    networks:
      - service-network

  database:
    image: postgis/postgis:17-3.4
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - GEOFENCE_DB_USER=postgres
      - GEOFENCE_DB_PASSWORD=postgres
      - GEOFENCE_DB_HOST=database
    volumes:
      - ./database-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/pg_hba.conf
    command: [ '-c', 'hba_file=/etc/pg_hba.conf' ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpu_count: 2
    networks:
      - service-network

networks:
  service-network:
    driver: bridge